name: create_S3_bucket
on: 
  push:

jobs:
  S3_deployment:
     runs-on: ubuntu-latest
     env:
       ACCESS_KEY100 : ${{secrets.ACCESS_KEY100}}
       SECRET_ACCES_KEY100: ${{secrets.SECRET_ACCES_KEY100}}
     steps:
       - name: setup Terraform
         uses: hashicorp/setup-terraform@v2
         with:
           terraform-version: 1.1.9
       - name: terraform init
         run: |
            terraform init
       - name: terraform validate
         run: |
            terraform validate
       - name: terraform plan
         run: |
            terraform plan
       - name: terraform apply
         run: |
            terraform apply -auto-approve
